name: Terraform Deployment

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.JENKINS_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.JENKINS_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  PUBLIC_SSH_KEY: ${{ secrets.PUBLIC_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, test, prod]

    defaults:
      run:
        working-directory: ./envs/${{ matrix.env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: List working directory contents
        run: ls -l

      - name: List env folder contents
        run: ls -l ./envs/${{ matrix.env }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -var-file="terraform.tfvars" -out=tfplan \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=$ARM_CLIENT_SECRET" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="vm_public_key=$PUBLIC_SSH_KEY"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
