name: Terraform Deployment

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.JENKINS_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.JENKINS_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  PUBLIC_SSH_KEY: ${{ secrets.PUBLIC_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug SSH Key
        run: |
          echo "Public key begins with:"
          echo "$PUBLIC_SSH_KEY" | cut -c1-40

      - name: Terraform Init
        run: |
          cd ./env/${{ matrix.environment }}
          terraform init

      - name: Terraform Validate
        run: |
          cd ./env/${{ matrix.environment }}
          terraform validate

      - name: Terraform Plan
        run: |
          cd ./env/${{ matrix.environment }}
          terraform plan -out=tfplan \
            -var="client_id=$ARM_CLIENT_ID" \
            -var="client_secret=$ARM_CLIENT_SECRET" \
            -var="tenant_id=$ARM_TENANT_ID" \
            -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var="vm_public_key=$PUBLIC_SSH_KEY" \
            -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./env/${{ matrix.environment }}
          terraform apply -auto-approve tfplan
